# Site settings
title: pedroamaral.pt
description: 'Software Engineer based in Porto'
url: 'www.pedroamaral.pt'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Pedro Amaral'
  email: pedr.amaral@gmail.com
  twitter_username: lockemind
  github_username:  lockemind
  linkedin_username:  pedramaral

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
